[package]
name = "minimal-k-isomorphic-subgraph-extension"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "exact-solver"
path = "src/bin/exact_solver.rs"

[[bin]]
name = "approx-solver"
path = "src/bin/approx_solver.rs"
